# 服务端口
server:
    port: 8007
# 服务名(cloud)
#spring.application.name=user

# 环境设置：dev、test、prod
spring:
    profiles:
        active: dev
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://rm-2ze4l01u0xqle8drn6o.mysql.rds.aliyuncs.com:3306/softeng?zeroDateTimeBehavior=convertToNull&amp
        username: maphsge7
        password: myroot@123
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB

mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:**/mapper/xml/*.xml

var:
    hour: 5
    minute: 45
    pos: 100
    fupos: -1



# 设置日志级别
#logging.level.root=INFO
#mybatis日志
